configuration:
  
  boundedContextName: "Dddml.Wms" #name: wms
  displayName: 仓库管理系统(Warehouse Management System)
  description: 仓库管理系统(Warehouse Management System)
  defaultModule: "Dddml.Wms" #namespace: org.dddml.wms
  audited: true
  hateoas: false
  baseUri: "/api"

  # -----------------------------------------
  java:
    boundedContextPackage: "org.dddml.wms" #namespace: org.dddml.wms
    specializationPackage: "org.dddml.wms.specialization"
    isUsingSeparatedDomainAggregatePackage: true
    defaultUserIdType: "string"

  # -----------------------------------------
  namedStringPatterns:
    "AttributeId": "^[\\(A-Za-z0-9][A-Za-z0-9]*"
  
  #genericTypes: ["TAccountId", "TQuantity"]
  #isGenericTypeAsType: true  
  #defaultTimestampType: "Timestamp"

  # -----------------------------------------
  accountingQuantityTypes:
    decimal:
      zeroLogic:
        Java: "BigDecimal.ZERO"
      addLogic:
        Java: "{fst}.add({snd} != null ? {snd} : BigDecimal.ZERO)"
      negateLogic:
        Java: "{0}.negate()"
                
  
  # -----------------------------------------
  defaultReservedProperties:
    active: Active
    createdBy: CreatedBy
    createdAt: CreatedAt
    updatedBy: UpdatedBy
    updatedAt: UpdatedAt
    deleted: Deleted
    version: Version
    
  # -----------------------------------------
  metadata:
    
    HttpServicesAuthorizationEnabled: false
    HttpPostCreationWithIdEnabled: true
    HttpPutToMergePatchEnabled: true
    
